import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import"./style.css";

const API=import.meta.env.VITE_API||"";
const req=async(path,opt={})=>{
 const r=await fetch(API+path,{credentials:"include",...opt});
 const j=await r.json().catch(()=>({}));
 if(!r.ok)throw Error(j.error||"Something went wrong");
 return j;
};

function App(){
 const[user,setUser]=useState(null),[page,setPage]=useState("home"),[form,setForm]=useState({name:"",email:"",password:""}),[msg,setMsg]=useState(""),[items,setItems]=useState([]),[photo,setPhoto]=useState(null);
 const go=p=>{setPage(p);setMsg("");window.scrollTo({top:0,behavior:"smooth"})};
 useEffect(()=>{req("/api/auth").then(x=>x.loggedIn&&setUser(x)).catch(()=>{})},[]);
 const login=async e=>{e.preventDefault();try{const x=await req("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setUser(x);go(x.role==="ADMIN"?"admin":"dashboard")}catch(e){setMsg(e.message)}};
 const register=async e=>{e.preventDefault();try{const x=await req("/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setUser(x);go("dashboard")}catch(e){setMsg(e.message)}};
 const load=()=>req(user?.role==="ADMIN"?"/api/admin/complaints":"/api/complaints").then(setItems).catch(e=>setMsg(e.message));
 const submit=async e=>{e.preventDefault();if(!user){go("login");return}const f=new FormData(e.target);if(photo)f.set("photo",photo);try{await req("/api/complaints",{method:"POST",body:f});setMsg("Report submitted successfully.");e.target.reset();setPhoto(null);load()}catch(e){setMsg(e.message)}};
 const update=async(id,status)=>{try{await req("/api/admin/"+id,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});load()}catch(e){setMsg(e.message)}};
 const logout=async()=>{await req("/api/auth",{method:"DELETE"});setUser(null);go("home")};
 return <><header><div className="brand" onClick={()=>go("home")}><b>♻</b>Clean<span>City</span></div><nav><button onClick={()=>go("home")}>Home</button><button onClick={()=>go("report")}>Report Waste</button><button onClick={()=>go("about")}>How It Works</button>{user&&<button onClick={()=>{go(user.role==="ADMIN"?"admin":"dashboard");load()}}>Dashboard</button>}{user?<button onClick={logout}>Logout</button>:<><button onClick={()=>go("login")}>Login</button><button className="navCta" onClick={()=>go("register")}>Get Started</button></>}</nav></header>
 <main>
 {page==="home"&&<Home go={go}/>}
 {page==="about"&&<About go={go}/>}
 {page==="login"&&<Auth title="Welcome back" sub="Sign in to manage your waste reports." button="Sign In" submit={login} form={form} setForm={setForm} msg={msg}/>}
 {page==="register"&&<Auth title="Create your account" sub="Join the community and help keep your city clean." button="Create Account" submit={register} form={form} setForm={setForm} register msg={msg}/>}
 {page==="report"&&<Report user={user} go={go} submit={submit} photo={photo} setPhoto={setPhoto} msg={msg}/>}
 {(page==="dashboard"||page==="admin")&&<Dashboard admin={page==="admin"} data={items} load={load} update={update}/>}
 </main><footer><div className="brand"><b>♻</b>Clean<span>City</span></div><p>Smart reporting for cleaner, healthier communities.</p><small>© 2026 CleanCity • Smart Waste Reporting System</small></footer></>
}

function Home({go}){return <><section className="hero"><div><label>SMART WASTE REPORTING SYSTEM</label><h1>A cleaner city starts with <em>one report.</em></h1><p>Spot waste? Report it in seconds with a photo, location and description. Help connect citizens with the people responsible for keeping our communities clean.</p><div className="actions"><button className="primary big" onClick={()=>go("report")}>Report Waste →</button><button className="secondary big" onClick={()=>go("about")}>Learn How It Works</button></div><div className="checks">✓ Easy to report &nbsp;&nbsp; ✓ Track progress &nbsp;&nbsp; ✓ Community focused</div></div><div className="visual"><div className="card"><div className="cardHead"><span>📍</span><div><b>Waste Report</b><small>Just now</small></div><i>Completed</i></div><div className="photo">♻️</div><div className="cardFoot">📍 Main Road, Mumbai <strong>✓ Resolved</strong></div></div><div className="float"><b>2,450+</b><small>reports helped</small></div></div></section><section className="strip"><div><b>01</b><strong>Capture</strong><p>Take a clear photo.</p></div><div><b>02</b><strong>Report</strong><p>Add location & details.</p></div><div><b>03</b><strong>Track</strong><p>Follow the progress.</p></div></section><section className="section"><label>WHY CLEANCITY?</label><h2>Small reports can create big change.</h2><p className="lead">CleanCity makes communication between citizens and waste-management teams simple, transparent and organized.</p><div className="features"><Feature icon="📸" t="Photo Evidence" p="Upload a clear image so the issue can be understood quickly."/><Feature icon="📍" t="Location Details" p="Provide the exact location for faster action."/><Feature icon="📊" t="Status Tracking" p="Know whether your complaint is pending, in progress or completed."/><Feature icon="🤝" t="Community Action" p="Work together to make public spaces cleaner and healthier."/></div></section><section className="cta"><div><label>MAKE A DIFFERENCE</label><h2>See waste? Don't ignore it.</h2><p>Your report can help bring attention to a problem that affects everyone.</p></div><button className="white big" onClick={()=>go("report")}>Start a Report →</button></section></>}

function Feature({icon,t,p}){return <article className="feature"><span>{icon}</span><h3>{t}</h3><p>{p}</p></article>}

function About({go}){return <section className="page"><label>HOW IT WORKS</label><h1>From problem to action.</h1><p className="lead">A simple four-step process designed for citizens and administrators.</p><div className="steps">{[["01","Report","Submit location, description and an optional photo."],["02","Review","An administrator reviews the incoming complaint."],["03","Action","The status moves from Pending to In Progress."],["04","Resolve","Once handled, the report is marked Completed."]].map(x=><article className="step"><b>{x[0]}</b><div><h3>{x[1]}</h3><p>{x[2]}</p></div></article>)}</div><div className="aboutCta"><div><h2>Ready to report a waste problem?</h2><p>It only takes a few moments.</p></div><button className="primary" onClick={()=>go("report")}>Start a Report →</button></div></section>}

function Report({user,go,submit,photo,setPhoto,msg}){return <section className="page"><label>REPORT AN ISSUE</label><h1>Report Waste</h1><p className="lead">Help us identify and address waste in your area.</p>{!user&&<div className="notice">🔐 Please <button onClick={()=>go("login")}>sign in</button> to submit a complaint.</div>}<div className="reportGrid"><form className="formBox" onSubmit={submit}><label>Location<input name="location" placeholder="e.g. Near Main Road, Mumbai" required/></label><label>Description<textarea name="description" placeholder="Describe the garbage issue..." required></textarea></label><label>Photo <small>(optional)</small><div className="upload">📷 <b>{photo?photo.name:"Upload a photo"}</b><small>JPG, PNG or WEBP</small><input type="file" accept="image/*" onChange={e=>setPhoto(e.target.files[0])}/></div></label>{msg&&<div className="message">{msg}</div>}<button className="primary submit" disabled={!user}>Submit Waste Report →</button></form><aside><div className="round">♻</div><h2>Why report?</h2><p>Timely reports help authorities identify problem areas and prioritize cleanup work.</p><hr/><p>✓ Clear photo helps verification</p><p>✓ Accurate location speeds response</p><p>✓ Track your complaint online</p></aside></div></section>}

function Auth({title,sub,button,submit,form,setForm,register,msg}){return <section className="auth"><div className="authBox"><div className="authIcon">♻</div><label>CLEANCITY</label><h1>{title}</h1><p>{sub}</p><form onSubmit={submit}>{register&&<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full name" required/>}<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="Email address" required/><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Password" required/>{msg&&<div className="message error">{msg}</div>}<button className="primary submit">{button} →</button></form></div></section>}

function Dashboard({admin,data,load,update}){return <section className="page"><label>{admin?"ADMINISTRATION":"MY ACTIVITY"}</label><div className="dashHead"><div><h1>{admin?"Complaint Management":"My Complaints"}</h1><p>{admin?"Review reports and update their progress.":"Track the waste reports you have submitted."}</p></div><button className="primary" onClick={load}>↻ Refresh</button></div>{!data.length?<div className="empty"><b>♻</b><h2>No complaints yet</h2><p>Submitted waste reports will appear here.</p></div>:<div className="list">{data.map(x=><article><div><strong>Waste Complaint #{x.id}</strong><p>{x.description}</p><small>📍 {x.location}</small><small>🕒 {x.created_at||""}</small></div><div className="side"><span className={"status "+String(x.status).toLowerCase().replace(" ","-")}>{x.status}</span>{admin&&<select value={x.status} onChange={e=>update(x.id,e.target.value)}><option>Pending</option><option>In Progress</option><option>Completed</option></select>}</div></article>)}</div>}</section>}

createRoot(document.getElementById("root")).render(<App/>);
